library('RPostgreSQL')
drv_generic <- dbDriver("PostgreSQL")
conn <- dbConnect(drv=drv_generic, "localhost", port = 5432, user = "pbaz", password = "pbaz", dbname = "pbaz")

dbSendStatement(conn, "DROP VIEW clim_pheno")
dbSendStatement(conn, "DROP VIEW clim_pheno_of")
dbSendStatement(conn, "DROP VIEW clim_pheno_o_f_1")
dbSendStatement(conn, "DROP VIEW clim_pheno_o_s_f_m")
dbSendStatement(conn, "DROP VIEW clim_pheno_o_s_f")
dbSendStatement(conn, "DROP VIEW clim_pheno_o_f")
dbSendStatement(conn, "DROP VIEW clim_pheno_t")
dbSendStatement(conn, "DROP VIEW phase_transition_time")
	dbSendStatement(conn, "DROP VIEW rp5_sowing_to_seedlings10")
	dbSendStatement(conn, "DROP VIEW rp5_sowing_to_seedlings75")
	dbSendStatement(conn, "DROP VIEW rp5_seedlings75_to_flowering10")
	dbSendStatement(conn, "DROP VIEW rp5_flowering75_to_maturityFull")
	dbSendStatement(conn, "DROP VIEW rp5_sowing")
	dbSendStatement(conn, "DROP VIEW rp5_sowing_5x5")
	dbSendStatement(conn, "DROP VIEW rp5_sowing_x10")
	dbSendStatement(conn, "DROP VIEW rp5_sowing_10x")
	dbSendStatement(conn, "DROP VIEW rp5_seedlings10")
	dbSendStatement(conn, "DROP VIEW rp5_seedlings10_5x5")
	dbSendStatement(conn, "DROP VIEW rp5_seedlings10_x10")
	dbSendStatement(conn, "DROP VIEW rp5_seedlings10_10x")
	dbSendStatement(conn, "DROP VIEW rp5_seedlings75")
	dbSendStatement(conn, "DROP VIEW rp5_seedlings75_5x5")
	dbSendStatement(conn, "DROP VIEW rp5_seedlings75_x10")
	dbSendStatement(conn, "DROP VIEW rp5_seedlings75_10x")
	dbSendStatement(conn, "DROP VIEW rp5_flowering10")
	dbSendStatement(conn, "DROP VIEW rp5_flowering10_5x5")
	dbSendStatement(conn, "DROP VIEW rp5_flowering10_x10")
	dbSendStatement(conn, "DROP VIEW rp5_flowering10_10x")
	dbSendStatement(conn, "DROP VIEW rp5_maturityFull")
	dbSendStatement(conn, "DROP VIEW rp5_maturityFull_5x5")
	dbSendStatement(conn, "DROP VIEW rp5_maturityFull_x10")
	dbSendStatement(conn, "DROP VIEW rp5_maturityFull_10x")

dbDisconnect(conn)
